

# n = [19, 17, 12, 17, 17, 18, 10, 17, 14, 12, 19, 17, 12, 13, 11] 
# i=0
# a=[]
# b=[]
# s=[]
# while i<len(n):
#     j=0
#     c=0
#     while j<len(n):
#         if n[i]==n[j]:
#             a.append(n[i])
#             c=c+1
#         j=j+1
#     k=0
#     while k<1:
#         if n[i]not in b:
#             b.append(n[i])
#             print(n[i],"times",c)
#             s.append([n[i],"=",c])
#         k=k+1
#     i=i+1
# print(s)