# kitane_crorepati
# kph=[3000,600000,324990909,90990900,30000,5600000,690909090,31010101,532010,510,4100]
# i=0
# count=0
# while i<len(kph):
#     if kph[i]>10000000:
#         count=count+1
#     i=i+1
# print(count,"crorepati")
# j=0
# count=0
# while j<len(kph):
#     if kph[j]<10000:
#         count=count+1
#     j=j+1
# print(count,"lakhpati")
# k=0
# count=0
# while k<len(kph):
#     if kph[k]<100000:
#         count=count+1
#     k=k+1
# print(count,"dilwale")